name: stackfood_sample_task
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+100

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.3.2
  http: ^1.5.0
  get_storage: ^2.1.1
  flutter_svg: ^2.2.1
  app_tracking_transparency: ^2.0.6+1
  cached_network_image: ^3.4.1
  intl: ^0.20.2
  skeletonizer: ^2.1.0+1
  device_info_plus: ^12.2.0
  haptic_feedback: ^0.5.1+1
  firebase_crashlytics: ^5.0.3
  firebase_messaging: ^16.0.3
  firebase_core: ^4.2.0
  onesignal_flutter: ^5.3.4
  awesome_notifications: ^0.10.1
  fluttertoast: ^9.0.0
  smooth_page_indicator: ^1.2.1
  carousel_slider: ^5.1.1
  package_info_plus: ^9.0.0
  flutter_expanded_tile: ^0.4.0
  pinput: ^5.0.2
  flutter_inner_shadow: ^0.0.1
  flutter_rating_bar: ^4.0.1
  google_sign_in: ^7.2.0
  sign_in_with_apple: ^7.0.1
  flutter_widget_from_html: ^0.17.1
  share_plus: ^12.0.1
  image_picker: ^1.2.0
  image_cropper: ^11.0.0
  http_parser: ^4.1.2
  pod_player: ^0.2.2
  google_mobile_ads: ^6.0.0
  purchases_flutter: ^9.9.1
  url_launcher: ^6.3.2
  flutter_staggered_grid_view: ^0.7.0
  webview_flutter: ^4.13.0
  unity_ads_plugin: ^0.3.28
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  path: ^1.9.1
  scrollable_positioned_list: ^0.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
