name: stackfood_sample_task
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+100

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.3.2
  http: ^1.5.0
  get_storage: ^2.1.1
  flutter_svg: ^2.2.2
  app_tracking_transparency: ^2.0.6+1
  cached_network_image: ^3.4.1
  intl: ^0.20.2
  skeletonizer: ^2.1.0+1
  haptic_feedback: ^0.5.1+1
  fluttertoast: ^9.0.0
  smooth_page_indicator: ^1.2.1
  carousel_slider: ^5.1.1
  flutter_inner_shadow: ^0.0.1
  image_picker: ^1.2.0
  http_parser: ^4.1.2
  url_launcher: ^6.3.2
  flutter_staggered_grid_view: ^0.7.0
  scrollable_positioned_list: ^0.3.8
  device_info_plus: ^12.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
